Title: BioCypher graph schema configuration file

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database.

Node:
  Molecule:
    Protein:
      preferred_id: uniprot
    miRNA:
      preferred_id: mirbase_name
    ChemicalCompound:
      Drug:
        preferred_id: pubchem

  Complex:
    preferred_id: complex_id

  Annotation:
    Species:
      preferred_id: taxon_id
    Evidence:
      Literature:
        preferred_id: pmid
      HighThroughput:
        preferred_id: assay_id

EDGE:
  POST_TRANSLATIONAL:
    Protein: Protein
  POST_TRANSCRIPTIONAL:
    miRNA: Protein