Title: BioCypher graph schema configuration file

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database.

Node:
  Protein:
    preferred_id: uniprot
  miRNA:
    preferred_id: mirbase_name
  Species:
    preferred_id: taxon_id

EDGE:
  POST_TRANSLATIONAL:
    Protein: Protein
  POST_TRANSCRIPTIONAL:
    miRNA: Protein