Title: BioCypher python module configuration file

# Neo4j connection using credentials
neo4j_uri: neo4j://localhost:7687
neo4j_db: neo4j # DB name
neo4j_user: neo4j # user name
neo4j_pw: your_password_here # password
# TODO Neo4j desktop does not allow setting 'neo4j' as a password!

# Neo4j admin import batch writer settings
neo4j_delimiter: '¦'
neo4j_array_delimiter: '|'
neo4j_quote_char: "'"

# Path to the log directory
logdir: biocypher-log

# Logging granularity
# Set debug to true if more granular logging is desired
debug: true

# Path to the output directory
outdir: biocypher-out
