Title: BioCypher python module configuration file

# Neo4j connection credentials
neo4j_uri: neo4j://localhost:7687
neo4j_db: neo4j # DB name
neo4j_user: neo4j # user name
neo4j_pw: neo4j # password
neo4j_insert_batch_size: 30000


# Neo4j admin import batch writer settings
csv_delimiter: '¦'
csv_array_delimiter: '|'
csv_quote_char: '"'
csv_batch_size: 1000000

# Offline mode: do not connect to a running Neo4j instance
# Can be used e.g. for writing CSV files for admin import
offline: true

# Logging granularity
# Set debug to true if more granular logging is desired
debug: true

# Set to change the log directory
logdir: biocypher-log

# Set to change the output directory
outdir: biocypher-out
cachedir: null

# Clear ontology cache
# BioCypher caches the ontology scaffold for performance reasons
# Set to true to clear the cache and re-download the ontology
clear_cache: false
