Title: BioCypher graph schema configuration file

# This configuration file establishes the hierarchy and connectivity in a newly
# set-up BioCypher property graph database.

Molecule:
  Protein:
    represented_as: node
    preferred_id: uniprot
  miRNA:
    represented_as: node
    preferred_id: mirbase_name
  ChemicalCompound:
    Drug:
      represented_as: node
      preferred_id: pubchem

Complex:
  represented_as: node
  preferred_id: complex_id

Annotation:
  Species:
    represented_as: node
    preferred_id: taxon_id
  Evidence:
    Literature:
      represented_as: node
      preferred_id: pmid
    HighThroughput:
      represented_as: node
      preferred_id: assay_id

Interaction:
  PostTranslational:
    # higher-level preferred_ids?
    Phosphorylation:
      represented_as: edge
      preferred_id: tba
      source: Protein
      target: Protein
    Acetylation:
      represented_as: edge
      preferred_id: tba
      source: Protein
      target: Protein
      
  PostTranscriptional:
    RISCDependent:
      represented_as: edge
      preferred_id: tba
      source: miRNA
      target: Protein

  DiseaseAssociation:
    represented_as: edge
    preferred_id: tba
    source: Protein
    target: Disease


## CROssBAR list of source database attributes
# UniProtKB (related MongoDB collections: Proteins):
# accession(protein,UniProt)
# ec
# fullName
# gene(symbol)
# go
# interpro
# omim
# orphanet
# pfam
# reactome
# taxId

# IntAct (related MongoDB collections: Intact):
# accession(protein,UniProt)
# confidence
# gene(symbol)

# EFO (related MongoDB collections: EFO disease terms):
# doid
# label
# mesh
# oboId
# omimId
# synonym

# HPO (related MongoDB collections: HPO):
# genesymbol
# hpotermname
# synonym

# ChEMBL (related MongoDB collections: Molecules, Targets, Assays, Activities):
# assayChemblId
# assayType
# assayOrganism
# moleculeChemblId
# canonicalSmiles
# inchiKey
# pchemblValue
# targetChemblId
# accession(protein,UniProt)
# targetIds
# DrugBank (related MongoDB collections: Drugs):
# accession(target protein,UniProt)
# chemblId
# identifier
# name
# pubchemCid

# PubChem (related MongoDB collections: PubChem Bioassay Sids, PubChem Biossays, PubChem Compounds, PubChem Substances):
# canonicalSmiles
# cid
# inchiKey
# accession(target protein,UniProt)
# assayPubchemId
# ncbiProteinId
# sids
# outcome