name: "Update Sphinx Autodoc on Push"
on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Build docs
      run: |
        pip3 install sphinx sphinx_rtd_theme
        cd docs
        make html
        cd ..
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f docs/_build/
        git commit -m "Update autodoc" -a
    # using https://github.com/marketplace/actions/push-git-subdirectory-as-branch
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/_build/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
